### ISSUE TITLE
Where is libnode?

### ISSUE THREAD

**Issue by 2505817596** [microsoft/node-api-dotnet#152] opened 2023-08-27 03:00 UTC
How do I get libnode?

**Comment by LunaticLunaLover69** [comment] 2023-09-12 00:47
push

**Comment by jasongin** [comment] 2023-09-17 10:19
Sorry, @vmoroz was working on getting it automatically built and published, but ran into some complications.

Longer term we'd like the Node.js project to own that build and publish process, but discussions about that haven't gotten very far yet. So I expect we will need to publish unofficial libnode binaries in the interim to support this project.

**Comment by jasongin** [comment] 2023-09-18 23:25
Closing as duplicate of https://github.com/microsoft/node-api-dotnet/issues/107

**Closed by jasongin** 2023-09-18 23:25 UTC
