### ISSUE TITLE
Cannot use node-api-dotnet with Microsoft.KernelMemory.Core 

### ISSUE THREAD

**Issue by trungklam** [microsoft/node-api-dotnet#175] opened 2023-11-10 05:13 UTC
I'm trying to create a .NET Node Module with [Microsoft.KernelMemory.Core ](https://www.nuget.org/packages/Microsoft.KernelMemory.Core/0.8.231108.2-preview), following this [Quickstart guide](https://github.com/microsoft/node-api-dotnet/blob/main/Docs/node-module.md)

Besides of adding `Microsoft.JavaScript.NodeApi` and `Microsoft.JavaScript.NodeApi.Generator`, I added `Microsoft.KernelMemory.Core`  into the project 
`dotnet add package Microsoft.KernelMemory.Core --version 0.8.231108.2-preview`

Then I got this build error. 
`
.nuget\packages\microsoft.javascript.nodeapi.generator\0.4.20\build\Microsoft.JavaScript.NodeApi.Generator.targets(34,5): error MSB3073: The command "dotnet "C:\Users\happiness\.nuget\packages\microsoft. 
javascript.nodeapi.generator\0.4.20\build\../analyzers/dotnet/cs/Microsoft.JavaScript.NodeApi.Generator.dll" -- assembly [a-lot-of-assembly] --module commonjs  --framework net6.0" exited with code 9020
`

I'm using Node 16 with .net 6.0. Any help will be much appreciated 😄

**Comment by jasongin** [comment] 2023-11-10 20:44
> [a-lot-of-assembly]

That is indeed a lot of referenced assemblies. I reproduced this error, and confirmed the assembly list is too long to pass on the command-line. So this is a duplicate of #148 

Since it is a blocking issue and you are not the only person to encounter it, I will raise the priority of that task. Hopefully we can resolve it soon.

**Closed by jasongin** 2023-11-10 20:44 UTC

**Comment by jasongin** [comment] 2023-11-11 01:06
Fixed and published to nuget as version `0.4.22`.

**Comment by trungklam** [comment] 2023-11-13 02:58
Thank you @jasongin , I can confirmed it works with new version 0.4.22
