### ISSUE TITLE
Cannot call base class method

### ISSUE THREAD

**Issue by Houfeng** [microsoft/node-api-dotnet#372] opened 2024-09-03 09:18 UTC
C#

```c#
[JSExport]
public class A {
  public virtual void Hello() {
  }
}

[JSExport]
public class B : A {
  public override void Hello() {
  }
}
```

JS
```ts
var b = new B();
b.hello();
```

Calling a base class method resulted in the following error

```
TypeError: Illegal invocation
```
  
Note: AOT enabled

**Comment by jasongin** [comment] 2024-09-04 03:23
@Houfeng I cannot reproduce the error so far. The code snippet above runs without error. Did you omit something critical when simplifying the code for the bug report?

Is there a stack trace with the error? It might include the .NET stack also.

**Comment by jasongin** [comment] 2024-09-16 20:04
Closing because there is not enough information to reproduce the error.

**Closed by jasongin** 2024-09-16 20:04 UTC
